create table if not exists public.companies (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    status text not null default 'active' check (status in ('active', 'inactive')),
    projected_amount numeric not null default 0,
    projected_notes text default '',
    activity_log text not null default '[]',
    created_at text not null
);

create table if not exists public.projects (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    status text default 'lead',
    start_date text,
    end_date text,
    warranty_start text,
    warranty_end text,
    pipeline_order integer default 0,
    company_id text references public.companies(id) on delete set null
);

create table if not exists public.tasks (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    project_id text references public.projects(id) on delete cascade,
    title text not null,
    description text,
    status text default 'todo',
    priority text default 'Media',
    due_date text
);

create table if not exists public.finances (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    concept text not null,
    type text not null check (type in ('income', 'expense')),
    amount numeric not null,
    date text not null,
    project_id text
);

create table if not exists public.activities (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    title text not null,
    "desc" text,
    date text not null
);

create table if not exists public.notes (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    title text not null,
    content text,
    folder text default 'General',
    color text default '#ffffff',
    created_at text not null
);

create table if not exists public.note_folders (
    id bigint generated by default as identity primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    unique (owner_id, name)
);

create table if not exists public.settings (
    owner_id uuid not null references auth.users(id) on delete cascade,
    key text not null,
    value text,
    primary key (owner_id, key)
);

create table if not exists public.integrations (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    type text not null default 'webhook',
    enabled boolean not null default true,
    config text not null default '{}',
    created_at text not null,
    updated_at text not null
);

create table if not exists public.integration_events (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    integration_id text references public.integrations(id) on delete cascade,
    event_type text not null,
    payload text,
    status text not null default 'sent',
    response text,
    created_at text not null
);

create table if not exists public.business_notifications (
    id text primary key,
    owner_id uuid not null references auth.users(id) on delete cascade,
    source text not null default 'gmail',
    label text not null default 'negocios',
    from_name text,
    from_email text,
    subject text not null default '',
    snippet text,
    body text,
    message_id text,
    thread_id text,
    url text,
    metadata text not null default '{}',
    received_at text not null,
    is_read boolean not null default false,
    notes text,
    created_at text not null,
    updated_at text not null
);

create index if not exists companies_owner_id_idx on public.companies (owner_id);
create index if not exists companies_status_idx on public.companies (status);
create index if not exists projects_owner_id_idx on public.projects (owner_id);
create index if not exists projects_company_id_idx on public.projects (company_id);
create index if not exists tasks_owner_id_idx on public.tasks (owner_id);
create index if not exists tasks_project_id_idx on public.tasks (project_id);
create index if not exists tasks_status_idx on public.tasks (status);
create index if not exists finances_owner_id_idx on public.finances (owner_id);
create index if not exists finances_date_idx on public.finances (date desc);
create index if not exists activities_owner_id_idx on public.activities (owner_id);
create index if not exists activities_date_idx on public.activities (date desc);
create index if not exists notes_owner_id_idx on public.notes (owner_id);
create index if not exists notes_created_at_idx on public.notes (created_at desc);
create index if not exists note_folders_owner_id_idx on public.note_folders (owner_id);
create index if not exists projects_pipeline_order_idx on public.projects (pipeline_order asc);
create index if not exists integrations_owner_id_idx on public.integrations (owner_id);
create index if not exists integrations_updated_at_idx on public.integrations (updated_at desc);
create index if not exists integration_events_owner_id_idx on public.integration_events (owner_id);
create index if not exists integration_events_created_at_idx on public.integration_events (created_at desc);
create index if not exists integration_events_integration_id_idx on public.integration_events (integration_id);
create index if not exists business_notifications_owner_id_idx on public.business_notifications (owner_id);
create index if not exists business_notifications_received_at_idx on public.business_notifications (received_at desc);
create index if not exists business_notifications_label_idx on public.business_notifications (label);
create index if not exists business_notifications_is_read_idx on public.business_notifications (is_read);

-- Nota: las carpetas de notas por defecto ('General', 'APIs', 'Contraseñas')
-- ya no se insertan aquí -- cada usuario nuevo las recibe automáticamente
-- la primera vez que carga el CRM (ver /api/state en server.js), porque
-- ahora son por-usuario, no globales.

-- Seguridad (SEC-02): el backend (server.js) habla con Supabase usando la
-- SUPABASE_SERVICE_ROLE_KEY, que ignora RLS por diseño. El navegador nunca
-- debe tener una vía directa a estas tablas, así que NO se le concede nada
-- al rol "anon" y se activa RLS en todas las tablas. Además de RLS, cada
-- ruta de server.js filtra explícitamente por owner_id -- esa es la
-- protección real (multi-cuenta), RLS es una segunda capa. Ver también
-- supabase/migrations/001_enable_rls.sql, 002_add_companies.sql y
-- 003_multi_tenant.sql si estás aplicando esto sobre un proyecto que ya
-- tenía las tablas creadas con el esquema anterior (de un solo usuario).
grant usage on schema public to authenticated;
grant select, insert, update, delete on
    public.companies,
    public.projects,
    public.tasks,
    public.finances,
    public.activities,
    public.notes,
    public.note_folders,
    public.settings,
    public.integrations,
    public.integration_events,
    public.business_notifications
to authenticated;

alter table public.companies enable row level security;
alter table public.projects enable row level security;
alter table public.tasks enable row level security;
alter table public.finances enable row level security;
alter table public.activities enable row level security;
alter table public.notes enable row level security;
alter table public.note_folders enable row level security;
alter table public.settings enable row level security;
alter table public.integrations enable row level security;
alter table public.integration_events enable row level security;
alter table public.business_notifications enable row level security;

create policy "owner_full_access" on public.companies for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner_full_access" on public.projects for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner_full_access" on public.tasks for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner_full_access" on public.finances for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner_full_access" on public.activities for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner_full_access" on public.notes for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner_full_access" on public.note_folders for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner_full_access" on public.settings for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner_full_access" on public.integrations for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner_full_access" on public.integration_events for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "owner_full_access" on public.business_notifications for all to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
